name: DenoriaUtils
version: '${version}'
main: dev.norbiros.denoriautils.DenoriaUtils
api-version: '1.19'
authors: [Norbiros]
depend:
  - MMOCore
  - MythicLib
  - Lands
  - Brewery
  - PlaceholderAPI